version: "3.5"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=your_admin_password
    volumes:
      - grafana_data:/var/lib/grafana

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: archflow
      POSTGRES_PASSWORD: archflow
      POSTGRES_DB: archflow
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "archflow" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  grafana_data:
  postgres_data:
