{
 "title": "Archflow Stats V2",
 "time": { "from": "2024-05-07T11:33:40.598Z", "to": "2024-05-07T11:34:42.204Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 0 },
   "options": {
    "content": " ▄▄▄        ██▀███    ▄████▄    ██░ ██    █████ ▒██▓      ▒█████    █     █░\n▒████▄     ▓██ ▒ ██ ▒▒██▀ ▀█   ▓██░ ██▒ ▓██   ▒ ▓██▒     ▒██▒  ██▒ ▓█░ █ ░█░\n▒██  ▀█▄   ▓██ ░▄█  ▒▒▓█    ▄  ▒██▀▀██░ ▒████ ░ ▒██░     ▒██░  ██▒ ▒█░ █ ░█ \n░██▄▄▄▄██  ▒██▀▀█▄   ▒▓▓▄ ▄██ ▒░▓█ ░██  ░▓█▒  ░ ▒██░     ▒██   ██░ ░█░ █ ░█ \n ▓█   ▓██▒ ░██▓ ▒██ ▒▒ ▓███▀  ░░▓█▒░██▓ ░▒█░    ░██████▒ ░ ████▓▒░ ░░██▒██▓ \n ▒▒   ▓▒█░ ░ ▒▓ ░▒▓ ░░ ░▒ ▒   ░ ▒ ░░▒░▒  ▒ ░    ░ ▒░▓  ░ ░ ▒░▒░▒░  ░ ▓░▒ ▒  \n  ▒   ▒▒ ░   ░▒ ░ ▒ ░  ░  ▒     ▒ ░▒░ ░  ░      ░ ░ ▒  ░   ░ ▒ ▒░    ▒ ░ ░  \n  ░   ▒      ░░   ░  ░          ░  ░░ ░  ░ ░      ░ ░    ░ ░ ░ ▒     ░   ░  \n      ░  ░    ░      ░ ░        ░  ░  ░             ░  ░     ░ ░       ░    "
   }
  },
  {
   "title": "AI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "AI Recommendation",
     "type": "stat",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "command": "get", "keyName": "chatgpt_recommendation", "type": "command" }
     ]
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Capacities",
     "type": "table",
     "gridPos": { "h": 16, "w": 19, "x": 2, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT * FROM node_capacity\nORDER BY node_name ASC"
      }
     ]
    }
   ]
  },
  { "title": "Grapg Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "In-Degree Centrality",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "command": "get", "keyName": "in_degree_centrality", "type": "command" }
   ]
  },
  {
   "title": "Out-Degree Centrality",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "command": "get", "keyName": "out_degree_centrality", "type": "command" }
   ]
  },
  {
   "title": "Closeness Centrality",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "targets": [
    { "command": "get", "keyName": "closeness_centrality", "type": "command" }
   ]
  },
  {
   "title": "Critical Link by Betweenness:",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    { "query": "LRANGE critical_links 0 -1", "type": "cli" }
   ]
  },
  { "title": "Simulation Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Average Percentage of Total Requests Per Node",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT node_name AS \"Node Name\",\r\n       AVG(percentage_of_total_hits) AS \"Average Percentage of Total Hits\"\r\nFROM node_hits\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY node_name"
    }
   ]
  },
  {
   "title": "SEIRT",
   "type": "stat",
   "description": "Seconds\nElapsed\nIn \nReal\nTime",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "global_timer", "type": "command" }
   ]
  },
  {
   "title": "Total Hits",
   "type": "bargauge",
   "gridPos": { "h": 22, "w": 11, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT node_name AS \"Node Name\",\n       SUM(hits) AS \"Total Hits\"\nFROM node_hits\nWHERE $__timeFilter(timestamp)\nGROUP BY node_name\nORDER BY node_name ASC\n"
    }
   ]
  },
  {
   "title": "Markov Path's Traversed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "command": "get", "keyName": "paths_traversed", "type": "command" }
   ]
  },
  {
   "title": "Average Hits per Node",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(hits) AS \"Average Hits per Node\"\nFROM node_hits\nWHERE $__timeFilter(timestamp)"
    }
   ]
  },
  {
   "title": "Remaining Node Capacity (IOs)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('second', timestamp) AS \"time\",\n       node_name,\n       AVG(cpu_io_capacity)            AS cpu_io_capacity\nFROM node_remaining_capacity\nGROUP BY date_trunc('second', timestamp), node_name\nORDER BY \"time\" ASC;"
    }
   ]
  },
  {
   "title": "SUM OF HITS",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('second', timestamp) AS \"time\",  -- Group data by minute for simplicity\n  node_name,\n  AVG(hits) AS total_hits\nFROM\n  node_hits\nWHERE\n  timestamp >= NOW() - INTERVAL '5 minutes'\n  AND (node_name LIKE '%replicated%' OR node_name NOT LIKE '%replicated%')\n  AND node_name != 'n0'\nGROUP BY\n  \"time\", node_name\nORDER BY\n  \"time\" ASC;"
    }
   ]
  }
 ]
}